import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Plugin to copy node-pty after build
const copyNodePtyPlugin = {
	name: "copy-node-pty",
	setup(build) {
		build.onEnd(() => {
			const srcDir = path.join(__dirname, "node_modules", "node-pty");
			const destDir = path.join(__dirname, "node_modules_plugin", "node-pty");

			if (!fs.existsSync(srcDir)) {
				console.warn("⚠️  node-pty not found in node_modules");
				return;
			}

			// Create destination directory
			if (!fs.existsSync(destDir)) {
				fs.mkdirSync(destDir, { recursive: true });
			}

			// Copy necessary files
			const itemsToCopy = ["build", "lib", "package.json"];

			for (const item of itemsToCopy) {
				const src = path.join(srcDir, item);
				const dest = path.join(destDir, item);

				if (fs.existsSync(src)) {
					fs.cpSync(src, dest, { recursive: true });
				}
			}

			console.log("✓ Copied node-pty to node_modules_plugin/");
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	loader: {
		".css": "text",
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"node-pty",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	platform: "node",
	plugins: [copyNodePtyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
