/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

const { Plugin, Notice } = require('obsidian');

class ObsitermishellPlugin extends Plugin {
    async onload() {
        console.log('Obsitermishell plugin loading...');
        
        // Add ribbon icon
        this.addRibbonIcon('terminal', 'Open Terminal', () => {
            new Notice('Terminal plugin loaded successfully! (Test version without PTY)');
        });

        // Add command
        this.addCommand({
            id: 'open-terminal',
            name: 'Open Terminal',
            callback: () => {
                new Notice('Terminal would open here! This is a test version.');
            }
        });

        console.log('Obsitermishell plugin loaded successfully (test mode)');
    }

    onunload() {
        console.log('Obsitermishell plugin unloaded');
    }
}

module.exports = ObsitermishellPlugin;